# Generated by Django 5.0 on 2023-12-19 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receta',
        ),
    ]
