# Generated by Django 5.0 on 2023-12-27 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
    ]
